spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
jwt.secretKey: 8f9b2d3c5e7a1f0b4d6c8e2a4f6b8c0d1e3a5f7b9c1d3e5f7a9b1c3d5e7f9a1b
app:
  frontend:
    url: http://localhost:8080/frontend
