server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9002/codexa-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver  

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          model:  google/gemini-3-flash-preview #x-ai/grok-code-fast-1 #google/gemini-2.5-flash  #openai/gpt-5.2-codex #qwen/qwen3-coder:free
          temperature: 0.0 #0.0 for deterministic output, higher values for more creativity
      # embedding:
      #   options: google/gemini-3-flash-preview    
      #   temperature: 0.2
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-v3.1:671b-cloud #qwen3-coder:480b-cloud #qwen3.5:cloud #qwen3:8b
          temperature: 0.0  
      # embedding:
      #     options: google/gemini-3-flash-preview    
      #     temperature: 0.2     

  autoconfigure:
    exclude:
      #- org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration    

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.codexa-ai.svc.cluster.local:5432/intelligence_db
    username: intelligence_user
    password: ${DB_PASSWORD}

  ai:
    openai:
      api-key: ${AI_API_KEY}
      chat:
        options:
          model:  google/gemini-3-flash-preview 
          temperature: 0.0  

    ollama:
      base-url: http://ollama.codexa-ai.svc.cluster.local:11434
      chat:
        options:
          model: deepseek-v3.1:671b-cloud
          temperature: 0.0      
