server:
  port: 9020
  servlet.context-path: /workspace

spring:
  datasource:
    url: jdbc:postgresql://localhost:9002/codexa-workspace-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects


---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://pgvector.codexa-ai.svc.cluster.local:5432/workspace_db
    username: workspace_user
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379  

minio:
  url: http://minio.codexa-ai.svc.cluster.local:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  project-bucket: projects       

---

spring:
  config:
    activate:
      on-profile: render
  datasource:
    url: ${SPRING_DATASOURCE_URL:http://workspace-service}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  project-bucket: ${MINIO_PROJECT_BUCKET}

  
    

